### ISSUE TITLE
Improve Hover Effect on Technology Icons for Colorful Logo Display

### ISSUE THREAD

**Issue by damnanuj** [saadpasta/developerFolio#741]
### Summary

Enhance the hover effect on the technology stack icons to display their original, colorful logos instead of the current blue tint. This change will provide a more visually appealing and brand-authentic representation of each technology logo.

### What's new?

This proposal suggests modifying the existing hover effect on the tech stack icons. Instead of the current blue color overlay, each icon should show its original colors when hovered over, aligning with the official branding of each technology.

### Motivation

It will create a more professional look, staying true to the identity of each technology.
A more user-friendly, visually consistent UI that enhances the user experience and clearly communicates the technologies used.

**Comment by damnanuj** [comment]
![image](https://github.com/user-attachments/assets/36473bed-5c58-440c-a413-5e11ac4cfab3)

**Comment by sufiankhan-dev** [comment]
Assign this to me! I'll improve this one

**Comment by MJBranco18** [comment]
I have fixed this. There is a PR here: https://github.com/saadpasta/developerFolio/pull/776

**Comment by Yeshwanth-kr** [comment]
But in the website, the icons are still in blue when hovered.

**Comment by aditya-jsx** [comment]
@damnanuj can i work on this?,
On the website the icons still appear blue while hovering.
